spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:snowflake://fea56695.us.east-1.snowflakecomputing.com/?warehouse=COMPUTE_WH&db=txn_db&schema=PUBLIC
    username: 
    password: 
    driverClassName: com.snowflake.client.jdbc.SnowflakeDriver
server:
   port: 9000